# Generated by Django 4.0 on 2022-04-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_details_service_id'),
        ('blog', '0002_alter_document_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='services.service'),
        ),
        migrations.AlterField(
            model_name='master_question',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_question', to='services.service_details'),
        ),
        migrations.AlterField(
            model_name='sub_question',
            name='QUESTION_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_question', to='blog.master_question'),
        ),
        migrations.AlterField(
            model_name='sub_question',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_question', to='services.service_details'),
        ),
    ]
